version: "3.8"
services:
  recipe-db:
    image: "mysql:latest"
    restart: on-failure
    environment:
      #      MYSQL:DATABASE: 'recipe-db'
      MYSQL_ROOT_PASSWORD: 'mypass'
    ports:
      - "3305:3306"
    networks:
      - springmysql-network
  app-client:
    build:
      context: src/client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"

  app-server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - recipe-db
    networks:
      - springmysql-network
networks:
  springmysql-network:
